In [42]:
import numpy as np 

a = np.array(range(0,10), dtype='float16')
print(a)
np.random.shuffle(a)
print(a)
print a.ndim
print a.dtype
print a.size
print '------------------'
b = np.arange(10)
print b
b = np.arange(10,30,5)
print b

c = b
c[0] = 100
print b

print a[3:5]

print '------------------'
aa = range(0, 10)
bb = range(10, 15)
d = []
d += aa
print d
d += bb
print d

np.random.shuffle(aa)
print aa

print '------------------'
aaa = np.reshape(aa, (len(aa),1))
print aa
print aaa
print np.shape(aaa)
print np.shape(aa)[0]

import tensorflow as tf
tf.Variable(tf.random_normal([10, 1]))


[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9.]
[ 5.  2.  7.  8.  3.  9.  1.  0.  4.  6.]
1
float16
10
------------------
[0 1 2 3 4 5 6 7 8 9]
[10 15 20 25]
[100  15  20  25]
[ 8.  3.]
------------------
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14]
[8, 3, 5, 9, 4, 0, 2, 6, 7, 1]
------------------
[8, 3, 5, 9, 4, 0, 2, 6, 7, 1]
[[8]
 [3]
 [5]
 [9]
 [4]
 [0]
 [2]
 [6]
 [7]
 [1]]
(10, 1)
10


ValueError: Tensor conversion requested dtype float64 for Tensor with dtype float32: 'Tensor("random_normal_2:0", shape=(10, 1), dtype=float32)'